Testing nodejs endpoint
jdinartejesus/guitar-star pull request #2
Opened 2017-01-21 11:31 UTC by jdinartejesus

2017-01-21 17:06 UTC, mikehenrty requested changes
This is a great start! I like the simplicity.

That said, there are a couple of things we need to decide before moving forward here:

1.) What does it mean to fail a test? Right now we are just `console.log('error', foo)`, but if we were running multiple tests at once, how is the error runner going to know if the test failed or not. So, we need to put the test itself into a function that either returns an error or throws an error.
2.) We should also consider that your whole test file could be run as part of a suite of tests. In which case, instead of just logging things to the console, we need to consider using your programs exit status. Ie. if one or more tests fail, return a failure code. See here for more details: http://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/
3.) We should also put things into library's whenever possible. For this first commit, I think a good library to make would be something that does assertions, so you can import `var assert = require('lib/assert');` then do something like `assert(res.statusCode, 200)` rather than using an if statement. We can look at the source of Chai to see how to do something like this.

Let me know if this makes sense.

2017-01-22 15:26 UTC, mikehenrty reviewed
Good progress! I have a couple more things:

* let's move `index.js` to a folder called `tests` and rename it to `test-api.js` or something more specific.
* Let's rename the `utils.js` file to `assert.js`, and move it to `/tests/lib/`. This way we will only put assert functionality in this file rather than a bunch of other stuff. then, make `module.exports` = your object rather than `module.exports.assert`.
* let's also create a new test helper library that will do similar things to what mocha does. we can put it in `/tests/lib/`, and the idea is that we can give it a series of functions to be evaluated, and the helper can keep track of which tests failed and succeded. The api could look something like this:
```
const runner = require('/tests/lib/runner');

runner.test('base api should return 200 status code', () => {
  http.get(......
 .....
});
```
# Style Comments
* It's generally considered good style practice to use semi-colons.
* Using const for imports doesn't feel right to me (although technically they are fine). const usually signifies a piece of memory is immutable (can't be changed), but a lot of nodejs modules have internal state that changes. Again, this is only a suggestion, but var or let to me makes more sense.

2017-01-22 15:26 UTC, mikehenrty commented on utils.js
> +  equal: function (condition1, condition2, message) {
let's rename `condition1` and `condition2` to `value1` and value2` since they are not actually conditional statements but values to be compared.

2017-01-22 15:26 UTC, mikehenrty commented on index.js
> +const http = require('http')
let's add a const for your base path:
```
const BASE_URL = 'http://localhost:8080' (or something)
```

2017-01-22 15:26 UTC, mikehenrty commented on index.js
> +http.get('/', (res) => {
We need to add a domain to this get request. See above comment about adding BASE_URL.

2017-01-25 20:22 UTC, jdinartejesus commented
Great, gonna do that. Thanks for the feedback.  About the semi-colons i'm using this http://standardjs.com/ as code style so I can of lose the semi-colons 🤓. 

About the const you're right I just see everything doing and I guess never had thinking about it. Good catch 👍 

Today I'm pushing the new updates 😃

2017-01-25 23:34 UTC, jdinartejesus commented on tests/lib/runner.js
> +  test: function (message, fn) {
Still Missing some functionality, gonna work on this tomorrow.

2017-01-29 22:40 UTC, jdinartejesus commented
Done @mikehenrty,  please take a look when you find the time 👍

2017-01-30 15:36 UTC, mikehenrty requested changes
Great progress! Still have a couple blockers:
* test runner needs to be able to handle tests that fail or pass asynchronously
* let's add a package.json since this will be a nodejs project
* let's allow running test using `npm run` command (ie. `npm run tests` or something (see http://blog.npmjs.org/post/127671403050/testing-and-deploying-with-ordered-npm-run-scripts for more info)

2017-01-30 15:36 UTC, mikehenrty commented on tests/lib/assert.js
> +  equal (value1, value2, msg) {
suggestion: add linebreaks in between function definitions. it makes it easier to scan and read.

2017-01-30 15:36 UTC, mikehenrty commented on tests/lib/runner.js
> +    this.failures = 0
you don't need to count the failures manually, you have this value in `this.errors.length`

2017-01-30 15:36 UTC, mikehenrty commented on tests/test-api.js
> +  http.get(BASE_URL, (res) => {
uh oh, looks like we have a problem here. this test finishes asynchronously, but the tests are run synchronously. so ever though this http.get call fails (ECONNREFUSED), the test runner still thinks this test is passing `0 Failed, 1 Passed. we are doing to have to allow asynchronous testing here.

See here for some inspiration: https://mochajs.org/#asynchronous-code

2017-01-30 15:37 UTC, jdinartejesus commented on tests/lib/runner.js
> +    this.failures = 0
@mikehenrty good point! :+1:

2017-02-09 14:20 UTC, mikehenrty approved these changes
Looks great! We've got a working test runner now! I left some nits, and a couple of changes I'd like you to make around the final summary output. But once you do those, go ahead and merge this! I don't need to take another look.

2017-02-09 14:20 UTC, mikehenrty commented on tests/lib/assert.js
> +  _assert (value, msg) {
nit: it's also useful to have a basic assert function exposed publicly. having the underscore here usually denotes that the file is private.

2017-02-09 14:20 UTC, mikehenrty commented on tests/lib/runner.js
> +    process.nextTick(() => this._runTests())
nit: you can just say `process.nextTick(this._runTests.bind(this));`

2017-02-09 14:20 UTC, mikehenrty commented on tests/test-api.js
> +runner.test('base api should return 200 status code', () => {
nit: you can change the messages to be 'test should always fail' or something.

2017-02-09 14:20 UTC, mikehenrty commented on tests/test-api.js
> +runner.test('base api should return 200 status code', (done) => {
nit: here you can change the message to be something like 'test should always pass'

2017-02-09 14:20 UTC, mikehenrty commented on tests/lib/runner.js
> +    this.errors.forEach((error) => (process.stdout.write(`${error.msg} \n`)))
We need a more helpful error message here. What I would like to see is something like:
````
Failed: base api should return 200 status code, "connect CONNREFUSED"
```

2017-02-09 14:20 UTC, mikehenrty commented on tests/lib/runner.js
> +    process.stdout.write(`${this.failures} Failed ${this.success} Passed \n`)
please move this line above the error summaries, and add some line breaks. we need a way to easily distinguish between the output from the tests, and the final summary

2017-02-13 09:42 UTC, mikehenrty commented
Oh, and make sure you add `fixes #2` to the end of one of your commit messages so that it closes this bug :)

2017-02-18 11:56 UTC, closed without merging